export const ENDPOINTS = {
    USUARIOS: "/usuarios",
    PEDIDOS: "/pedidos",
    PRODUCTOS: "/productos",
    NOTIFICACIONES: "/notificaciones",
    HEALTH_CHECK: "/health-check",
    COTIZACIONES: "/cotizaciones"
}

export const SUB_ROUTES = {
    BY_ID: "/:id",
    BY_VENDEDOR_ID: "/vendedor/:vendedorId",
    NOTIFICACIONES: "/notificaciones",
    ESTADO: "/estado",
    HISTORIAL: "/historial",
    LOGIN: "/login",
    CONVERTIR: "/convertir"
}

export const COMPOSED_ROUTES = {
    // Usuarios
    USUARIO_BY_ID: ENDPOINTS.USUARIOS + SUB_ROUTES.BY_ID,
    USUARIO_NOTIFICACIONES: ENDPOINTS.USUARIOS + SUB_ROUTES.BY_ID + SUB_ROUTES.NOTIFICACIONES,
    USUARIO_LOGIN: ENDPOINTS.USUARIOS + SUB_ROUTES.LOGIN,
    // Pedidos
    PEDIDO_BY_ID: ENDPOINTS.PEDIDOS + SUB_ROUTES.BY_ID,
    PEDIDO_ESTADO: ENDPOINTS.PEDIDOS + SUB_ROUTES.BY_ID + SUB_ROUTES.ESTADO,
    PEDIDO_HISTORIAL: ENDPOINTS.PEDIDOS + SUB_ROUTES.BY_ID + SUB_ROUTES.HISTORIAL,
    PEDIDO_BY_VENDEDOR: ENDPOINTS.PEDIDOS + SUB_ROUTES.BY_VENDEDOR_ID,

    // Productos
    PRODUCTO_BY_ID: ENDPOINTS.PRODUCTOS + SUB_ROUTES.BY_ID,
    PRODUCTO_BY_VENDEDOR: ENDPOINTS.PRODUCTOS + SUB_ROUTES.BY_VENDEDOR_ID,

    // Notificaciones
    NOTIFICACION_BY_ID: ENDPOINTS.NOTIFICACIONES + SUB_ROUTES.BY_ID,
    NOTIFICACION_BY_USER: ENDPOINTS.NOTIFICACIONES + ENDPOINTS.USUARIOS + SUB_ROUTES.BY_ID,

    // Cotizaciones
    COTIZACION_CONVERTIR: ENDPOINTS.COTIZACIONES + SUB_ROUTES.CONVERTIR
}